version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "qwerty123"
    volumes:
      - /clickhouse:/var/lib/clickhouse

  nginx-logger:
    image: jagadam97/nginx-logger:latest
    environment:
      BATCH_SIZE: "10"
      BATCH_DELAY: "10"
      LOG_FILE_PATH: "/var/log/all_proxy_access.log"
      DB: "default"
      DB_USER: "default"
      DB_PASSWORD: "qwerty123"
      DB_HOST: "clickhouse"
      CLICKHOUSE_PASSWORD: "qwerty123"
    volumes:
      - /npm/data/logs:/var/log
